package td.demo.demoproject;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class RequestFormObjects  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Cusomer name ")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String customerName;
    
    @org.kie.api.definition.type.Label(value = "Request #")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String requestNum;
    
    @org.kie.api.definition.type.Label(value = "Request type ")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String requestType;
    
    @org.kie.api.definition.type.Label(value = "Status")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String status;

    public RequestFormObjects() {
    }

    public RequestFormObjects(java.lang.String requestNum, java.lang.String customerName, java.lang.String requestType, java.lang.String status) {
        this.requestNum = requestNum;
        this.customerName = customerName;
        this.requestType = requestType;
        this.status = status;
    }


    
    public java.lang.String getCustomerName() {
        return this.customerName;
    }

    public void setCustomerName(  java.lang.String customerName ) {
        this.customerName = customerName;
    }
    
    public java.lang.String getRequestNum() {
        return this.requestNum;
    }

    public void setRequestNum(  java.lang.String requestNum ) {
        this.requestNum = requestNum;
    }
    
    public java.lang.String getRequestType() {
        return this.requestType;
    }

    public void setRequestType(  java.lang.String requestType ) {
        this.requestType = requestType;
    }
    
    public java.lang.String getStatus() {
        return this.status;
    }

    public void setStatus(  java.lang.String status ) {
        this.status = status;
    }
}